
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 17 13:08:51 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INCREMENT = 18;
  public static final int CONST = 29;
  public static final int GEQUAL = 25;
  public static final int NUMCONST = 38;
  public static final int CASE = 47;
  public static final int NOTEQUAL = 23;
  public static final int CONTINUE = 49;
  public static final int LPAREN = 8;
  public static final int GREATER = 24;
  public static final int SEMI = 6;
  public static final int LESS = 26;
  public static final int MINUS = 12;
  public static final int DECREMENT = 19;
  public static final int RPAREN = 9;
  public static final int AND = 20;
  public static final int OR = 21;
  public static final int QMARK = 17;
  public static final int COMMA = 10;
  public static final int CLASS = 34;
  public static final int DIV = 14;
  public static final int PLUS = 11;
  public static final int IF = 42;
  public static final int DOT = 37;
  public static final int EOF = 0;
  public static final int RETURN = 32;
  public static final int EQUAL = 16;
  public static final int NEW = 36;
  public static final int error = 1;
  public static final int ISEQUAL = 22;
  public static final int MUL = 13;
  public static final int MOD = 15;
  public static final int BREAK = 48;
  public static final int IDENT = 39;
  public static final int VOID = 33;
  public static final int SWITCH = 46;
  public static final int COLON = 7;
  public static final int ELSE = 43;
  public static final int LBRACE = 2;
  public static final int LSQUARE = 4;
  public static final int LEQUAL = 27;
  public static final int READ = 31;
  public static final int WHILE = 45;
  public static final int CHARCONST = 40;
  public static final int RSQUARE = 5;
  public static final int RBRACE = 3;
  public static final int BOOLCONST = 41;
  public static final int EXTENDS = 35;
  public static final int PROG = 28;
  public static final int DO = 44;
  public static final int PRINT = 30;
}

